<?php

namespace App\Http\Requests\Admin\groupPost;

use Illuminate\Support\Str;
use Illuminate\Foundation\Http\FormRequest;

class groupPostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     */
    public function authorize(): bool
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array<string, \Illuminate\Contracts\Validation\ValidationRule|array<mixed>|string>
     */
    public function rules(): array
    {
        $id = null;
        if (request()->route()->id) {
            $id = request()->route()->id;
        }

        if (!empty($id)) {
            $rule =  [
                'title' => 'required|max:255|string|unique:group_post,title,' . $id,
                'slug' => 'required',
                'order' => 'required'
            ];
        } else {
            $rule =  [
                'title' => 'required|max:255|string|unique:group_post,title',
                'slug' => 'required',
                'order' => 'required'
            ];
        }

        return  $rule;
    }

    public function messages()
    {
        return [
            'title.required' => ':attribute không được để trống',
            'title.string' => ':attribute phải là kiểu chuỗi',
            'title.max' => ':attribute không được quá :max ký tự',
            'title.unique' => ':attribute đã tồn tại trong hệ thống',
            'slug.required' => ':attribute không được để trống',
            'type.required' => ':attribute không được để trống',
            'order.required' => ':attribute không được để trống',
        ]; // TODO: Change the autogenerated stub
    }

    public function attributes()
    {
        return [
            'title' => 'Tên nhóm tin tức',
        ]; // TODO: Change the autogenerated stub
    }

    protected function prepareForValidation(): void
    {
        $this->merge([
            'slug' => Str::slug($this->title),
        ]);
    }
}
